# Generated by Django 2.2.3 on 2020-12-11 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0012_next_evolution'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Next_evolution',
        ),
    ]
