# Generated by Django 2.2.3 on 2020-12-15 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0020_auto_20201214_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonentity',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vid_pokemon', to='pokemon_entities.Pokemon', verbose_name='покемон'),
        ),
    ]
