# Generated by Django 2.2.3 on 2020-12-16 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0021_auto_20201215_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonentity',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kind_pokemon', to='pokemon_entities.Pokemon', verbose_name='покемон'),
        ),
    ]
